service: sqs-poc

provider:
  name: aws
  runtime: python3.7
  stage: dev
  environment:
    QUEUE_NAME: !Ref PocQueue

functions:
  sender:
    handler: sender.handler
    events:
      - http:
          method: post
          path: send
  target:
    handler: target.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PocQueue
              - Arn
resources:
  Resources:
    PocQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "PocQueue"
  Outputs:
    pocQueueArn:
      Value: { Fn::GetAtt: [PocQueue, Arn] }
      Export:
        Name: pocQueueArn
    pocQueueName:
      Value: { Fn::GetAtt: [PocQueue, QueueName] }
      Export:
        Name: pocQueueName
    pocQueueUrl:
      Value: !Ref PocQueue
      Export:
        Name: PocQueueUrl